### ISSUE TITLE
bug(rust): AWS Credentials are not passed to underlying object_store

### ISSUE THREAD

**Issue by adamfaulkner-at** [lancedb/lancedb#1168]
### LanceDB version

0.4.14

### What happened?

Various behaviors lead me to believe that an `AwsCredential` provided to a `ConnectBuilder` does not actually get propagated to the correct places. When aws credentials are provided using environment variables, everything works as expected.

I suspect you are calling `object_store::aws::AmazonS3Builder::from_env()` somewhere you shouldn't be.

### Are there known steps to reproduce?

```
    let db = lancedb::connect("s3://my-bucket/lance").region("us-west-1").aws_creds(
        AwsCredential {
            key_id: KEY_ID.to_string(),
            secret_key: SECRET_KEY.to_string(),
            token: Some(TOKEN.to_string()),
        }).execute().await.unwrap();

    let table = db.open_table("all_rides").execute().await.unwrap();
```

This yields a `TableNotFound { name: "all_rides" }`. However, if I set environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` then it works correctly.

In another case, I tried to create a new table after providing an `AwsCredential` to a `ConnectBuilder`, and it explicitly complained about not having a credential provider.

**Comment by adamfaulkner-at** [comment]
(I'm sorry this is tagged as typescript; I could not figure out how to submit a rust bug)

**Comment by wjones127** [comment]
Hey @adamfaulkner-at, thanks for reporting this. I'm currently looking at refactoring how we handle object store configuration, so I'll see if we can resolve this at the same time.

I think part of the issue seems to be we don't necessarily propagate object store configuration from `Connection` to `Table`. So there's the credentials you pass here:

https://docs.rs/lancedb/latest/lancedb/connection/struct.ConnectBuilder.html#method.aws_creds

And then there's the ones here, inside of `ReadParams`:

https://docs.rs/lancedb/latest/lancedb/connection/struct.OpenTableBuilder.html#method.lance_read_params

**Comment by wjones127** [comment]
There also appeared to be several bugs in Lance, which I fixed here: https://github.com/lancedb/lance/pull/2147
