### ISSUE TITLE
bug(python): LanceDB on Cloud Run (GCP) using GCS bucket mount - Generic LocalFileSystem error

### ISSUE THREAD

**Issue by mnsRG** [lancedb/lancedb#1305]
### LanceDB version

v0.6.10

### What happened?

Hello, I am using LanceDB inside a Cloud Run instance on GCP, which is mounted on a GCS bucket (using FUSE). The LanceDB connection is using a local path `db = lancedb.connect(“vector_db/lancedb“)` which is mounted on a GCS bucket path `<bucket-name>/vector_db/lancedb`. 
So, I am not using directly `gs://<bucket-name>/vector_db/lancedb` to connect to the GCS bucket.
Also I am creating a table called `texts`.

However I get this error:

```
severity=ERROR message="fuse: *fuseops.CreateLinkOp error: function not implemented" 

ERROR: LanceError(IO): Generic LocalFileSystem error: Unable to copy file from /vector_db/lancedb/texts.lance/_versions/.tmp_4.manifest_710c8ec5-9856-4086-b8e3-ab180e751bf7 to /vector_db/lancedb/texts.lance/_versions/4.manifest: Function not implemented (os error 38), /home/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:609:54
```

Could you please let me know if there is a possible solution here?
Thank you

**Comment by wjones127** [comment]
In order to support atomic commits, the filesystem needs to support certain atomic operations. For local file system, we rely on [hard_link](https://doc.rust-lang.org/std/fs/fn.hard_link.html). This is an important feature, as without it your table could become corrupted.

GCS mounted with FUSE doesn't seem to have this, which is why it breaks. It seems like it supports rename[^1], so maybe it would work if we switched to a [rename]() syscall. But there doesn't seem to be an atomic `rename if not exists` syscall available in Rust that works across platforms. That's probably why we use hardlink instead. Maybe you could convince `gcsfuse` to support that?

[^1]: https://github.com/GoogleCloudPlatform/gcsfuse/issues/81

Is there a reason you aren't using GCS directly? Seems like it would be the simplest workaround.

**Comment by mnsRG** [comment]
Thanks for your response. Ok I see, as far as I understand GCS FUSE is not planning to support hard_link.
The main reason I need to use fuse mount mainly has to do with the general architecture of our application, but I also had the impression that using a `gs://` connection would be slower (I might be wrong here). It’s an option for sure, which as it seems I would have to implement. Would allowing for an optional `fuse_compatibility` argument when building the LanceDB connection be a possibility in the future (which would use a rename syscall instead of hard_link only when a user explicitly asks for it)?

**Comment by wjones127** [comment]
> I also had the impression that using a gs:// connection would be slower (I might be wrong here)

Unless GCS FUSE does some very fancy caching, I don't see why it would be any faster than directly using the GCS API.

> Would allowing for an optional fuse_compatibility argument when building the LanceDB connection be a possibility in the future (which would use a rename syscall instead of hard_link only when a user explicitly asks for it)?

It's something we could think about. Perhaps we could somehow dynamically detect which is supported by the filesystem.

> Also, do you think that the same problem would come up in a read-only setup too?

In a read-only setup, you shouldn't need this operation at all. It's just used when committing transactions to the table. So you could just use `gs://` for writes and use the FUSE for ready workloads if you preferred that.

**Comment by mnsRG** [comment]
Couldn’t find many resources but it seems that `gsutil` is actually faster than `gcsfuse`. 
Here is an interesting reference: https://gist.github.com/bobbae/1f1f2dcd3f9a2288fca56c9089d6ea37
In that case I guess that using `gs://` would be a better choice between the two anyway. Therefore I will simply convert some parts of my code to use `gsutil`. If you ‘re planning to support fuse you could probably leave the issue as open, otherwise you can close it as far as I ‘m concerned. Thanks
