### ISSUE TITLE
bug(python): Fail to delete rows due to `OSError: LanceError(IO)`

### ISSUE THREAD

**Issue by jiahuei** [lancedb/lancedb#1466]
### LanceDB version

v0.10.1

### What happened?

Row deletion on the attached table
[test_table.lance.zip](https://github.com/user-attachments/files/16330409/test_table.lance.zip)
 fails with this error:
`OSError: LanceError(IO): Execution error: External error: Execution error: LanceError(IO): Did not find any data files for schema: Field(id=-1, name=_rowaddr, type=uint64)`

**Comment by westonpace** [comment]
I've tracked this down to a bug involving scalar indexed scans, delete, and the new stable row ids.  This commit includes a small unit test reproducing the issue: https://github.com/lancedb/lance/commit/5421ea593ebac35116b95d11de1e44488ba1db03

If we call delete then we perform a filtered scan to get the row addresses to delete.
If the delete filter is on an indexed column then that filtered scan becomes an indexed scan
Indexed scans currently return the row id (and not the row address)

I think the fix is:

 * If there are no row id sequences then the scalar indexed scan should assume the row ids are the row addresses and simply rename the output column (or duplicate it if the caller wants both row id and row address)
 * If there are row id sequences then an indexed scan will first need to materialized then index to get the row ids and then do a lookup in the row id sequences to convert the row ids into row addresses

I think we can add that first path today and leave that second path as a todo item for stable row ids?

CC @wjones127 for confirmation / second opinion

**Comment by wjones127** [comment]
I have already created a fix for this for when using new stable row ids. But I didn't think this would affect users not trying out that experimental feature. Here is the fix for stable row ids: https://github.com/lancedb/lance/pull/2609

I can add a similar test for address style addresses.

**Comment by wjones127** [comment]
Confirmed that fix upstream will address this. We will be making a release soon with that fix.
