### ISSUE TITLE
Loosen Pylance version

### ISSUE THREAD

**Issue by Pipboyguy** [lancedb/lancedb#1475]
Is it possible to loosen the pylance version restriction? The pinning to 0.14.1 is causing a few issues on our package resolution to due subsequent dependency on legacy pyarrow versions.

**Comment by wjones127** [comment]
I think we will eventually be able to do this, once we docouple the Python package from pylance. However, right now, they are very tightly coupled. New features in LanceDB are often just features in pylance that we expose in a new API. So we can't loosen it very much right now.

That being said, in the next release of pylance we will loosen the pyarrow pin (https://github.com/lancedb/lance/pull/2597), so that should alleviate your issue.
