### ISSUE TITLE
bug(python): How is the return value '_distance' calculated? Whether I use L2 or cosine, '_distance' is always from small to large

### ISSUE THREAD

**Issue by oswardlx** [lancedb/lancedb#1739]
### What happened?

when create vector index i used l2 and cosine separately。but '_distance' is always from small to large

**Comment by wjones127** [comment]
> but '_distance' is always from small to large

ANN searches for the closest data points. Data points that are close to the query have a smaller distance. That's why they would be sorted from small to large.

Are the distance values different from what you expect? Can you provide specific examples of vectors and a query and what distance you expected versus what you got?
