### ISSUE TITLE
Add documentation / features on versioning

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#20]
- How adding new vectors creates a new incremental version
- How does vector search work with new versions
- How to roll back and reproduce results from previous versions
- How to list versions etc

**Comment by prrao87** [comment]
Hi, I've been playing with LanceDB and reading your blog posts over the last week or two, great work so far, I really think what you're building can be a game changer! I'm planning on writing a blog post comparing the ease of use and setup of LanceDB vs. established vector stores like Weaviate, and hopefully, even publish an example workflow with the new LangChain integration too 😄. All of this is while duly noting that the current API of LanceDB is very fluid and is subject to change, of course.

That being said, I have a couple of questions on the documentation and what it covers (and how it will evolve going forward):

1. I've read the [blog post on data versioning](https://blog.lancedb.com/building-a-time-machine-with-lance-3b14ab536232#:~:text=Lance%20is%20able%20to%20automatically,model%20performance%20across%20different%20versions.) in lance, and I presume lancedb piggy-backs off of this too. However, I'm not clear on how `mode=overwrite` works when all I want to do is *update* specific records + their vectors. Say I had version 1 of my db with `data = {"text": "Hello world 2023-05-05", "id": 1}`, and version 2 with `data = {"text": "Hello world 2023-05-06", "id": 1}`. Both versions have the same primary key `id`, but different texts that I want updated in the vectors. Can LanceDB handle such in-place upserts yet?

2. The IVF-PQ index works pretty good, and you did an awesome job explaining the basic [tuning methods in the docs](https://lancedb.github.io/lancedb/ann_indexes/). However, it is still a finicky to fine-tune the parameter size during testing and there all sorts of dimensionality-related errors thrown by `PyO3`, that are coming directly from Rust. It does make things just that little bit harder to debug during testing. Looking forward to trying out the HNSW implementation in due course!

3. I see now in version `0.1.2` that we can [dump an existing table to Arrow](https://github.com/lancedb/lancedb/blob/59014a01e064d40f84cbe346c02b6ca0932d971c/python/lancedb/table.py#L101) format (assuming we don't want to work with pandas). From that, based on the examples in the docs, I can then read it into DuckDB and run OLAP queries on the table. Is this the preferred way to run OLAP queries on semi-structured data in the future? Or is the intended way to have your own query engine in Rust that can run OLAP queries via its own query language/DSL without depending on DuckDB at all? While DuckDB is awesome in its own right, it was primarily designed for SQL, and from what I gather, LanceDB is designed to be sort of a "vector store" counterpart to DuckDB in the NoSQL world -- is this understanding misguided? It would be cool to know more about your roadmap on how DuckDB and LanceDB are meant to stand apart from each other (or work together in a seamless fashion over the long term).

Overall, this is really exciting, and very inspiring to see the pace with which you're building, not to mention, evangelizing Rust's amazing numerical & data engineering ecosystem along the way, thanks for the awesome work so far!😆

**Comment by jaichopra** [comment]
@prrao87 thanks for diving, giving detailed feedback & being an early adopter.. ❤️ 

1. We haven't implemented upserts yet, as we have a big backlog of high priority items at the moment (even more basic functionality to implement first). Upserts will also require some design thought on the API and we would be keen for your input -- i.e. have an explicit update/find and update API vs allowing for updating by passing in ID to the same API call.

2. Thanks for the feedback -- we have related tickets to propagate human readable error messages (on the Lance side) and we'd like to have a similar design in LanceDB ultimately to make it easier to debug in the relevant language, in this case Python. We're also working on improving our test coverage in the case that this is due to the rust side of things. We are also implementing DiskANN, HNSW is not planned as of yet, but if there is large enough demand we could revisit that.

3. It's preferred to use DuckDB for analytics queries right now, and we're big fans of DuckDB. LanceDB is focused on dev/production workloads for LLMs, search, which as you've mentioned includes vector search, but can also include full text search and analytics queries. We're undecided at the moment on whether we will have our own query engine in Rust, but as you've called out our core is also useful in an OLAP setting as well, its just a matter of priorities and demand from our users. DuckDB/LanceDB will have clear delineation in the long term -- we are designed for multi-modal AI/ML workloads from the ground up (with Lance), which means you can store/query on dense data/documents (images, videos, point clouds) with great performance.

**Comment by AyushExel** [comment]
Versioning is added to docs now - https://lancedb.github.io/lancedb/notebooks/reproducibility/
