### ISSUE TITLE
countRows() becomes inaccurate

### ISSUE THREAD

**Issue by LincolnCannon** [lancedb/lancedb#379]
The problem occurs in an AWS environment, using javascript Lambda and Dockerfile for execution, and S3 for storage. I try to run the lambda multiple times concurrently or serially to add embeddings. Afterwards, I call countRows() to verify that they were all added. But countRows() doesn't always return the correct count. On investigation, sometimes countRows() returns a lower number than the number of .lance files present in S3 -- although I've also seen this problem rectify itself (at least sometimes) when I wait and run countRows() again later. In Discord, changhiskhan mentioned that the problem could be related to table metadata caching, and asked that I file an issue here. Thanks.

**Comment by wjones127** [comment]
From your message on Discord:

> That sounds like a possibility. I started noticing the problem when attempting multiple asynchronous concurrent adds.

It seems like the likely explanation is that the concurrent adds may have made the in-memory representation of the table inconsistent. It doesn't sound like you hit this, since in the end you were able to find all the rows when reloading the table, but it's also possible right now for one transaction to overwrite another if they happen at exactly the same time.

We are improving our transaction conflict resolution, which will prevent the latter (more rare) issue. It will require some special handling for S3 specifically, because (unlike most object stores) it doesn't have any mechanism to make atomic transactions.

cc @gsilvestrin it seems like this might be partly rooted in the issues we are fixing around making methods mutate the table object consistently. That's definitely something we want to avoid, as I mentioned in [my comment about the race condition in the proposed changes](https://github.com/lancedb/lancedb/pull/407#discussion_r1286382641).

**Comment by LincolnCannon** [comment]
Thanks for sharing your insights. As I've imported larger data sets, it has become harder to confirm what's present and what's missing after concurrent imports. But the numbers still don't seem to be adding up correctly. And I suspect you may be right about transactions overwriting each other.

**Comment by wjones127** [comment]
> Any recommended workarounds for loading a large number of embeds into LanceDB on S3?

Right now, I think the best thing do do is have a single writer. If you need parallelism generating the embeddings, you can do a fan-out architecture, like described here: https://github.com/lancedb/lancedb/issues/213#issuecomment-1601197526

We are working on proper support for concurrent writes in S3, which will involve setting up a DynamoDB or Redis commit locking mechanism. (RFC: https://github.com/lancedb/lance/issues/1183) Should be ready in the next week or two, I think. Then you could freely write from multiple nodes without having to manage the coordination yourself.

**Comment by LincolnCannon** [comment]
Thanks for the recommendation and update!

**Comment by changhiskhan** [comment]
@wjones127 does anything additional need to be implemented here or exposed to lancedb?

**Comment by wjones127** [comment]
I think it *should* already be exposed to LanceDB, but we should document it. Here's the corresponding Lance doc: https://lancedb.github.io/lance/read_and_write.html#concurrent-writer-on-s3-using-dynamodb

**Comment by changhiskhan** [comment]
@wjones127 / @LincolnCannon i think we can close this as resolved?

**Comment by LincolnCannon** [comment]
Yes. Thanks!
