### ISSUE TITLE
feat: enable dynamodb commit in python sdk

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#534]
# Problem Statement

We already support Dynamodb for strong consistency S3 commit in Rust and typescript SDK. We should bring it to Python as well.

**Comment by wjones127** [comment]
The existing Rust + Typescript one claims that it's not a stable public facing API. It is not documented. We should stabilize and document it.

**Comment by sandias42** [comment]
Just chiming in that some mechanism for safe concurrent writes to S3 in the python API is make or break for my company switching to LanceDB. 

Loving the project so far!!

**Comment by huffmanjohnf** [comment]
> some mechanism for safe concurrent writes to S3 in the python API is make or break for my company

Same here!

I'm not sure if this is the best place to drop some notes, but I was looking through the [related, closed issue](https://github.com/lancedb/lancedb/issues/1077#issuecomment-1985902354) which pointed to the [committing mechanism for s3](https://lancedb.github.io/lance/read_and_write.html#committing-mechanisms-for-s3) that Lance supports.

It does not work out-of-the-box with LanceDB because of how LanceTable's [`_dataset_uri` property is constructed](https://github.com/lancedb/lancedb/blob/python-v0.8.2/python/python/lancedb/table.py#L925-L927). It simply joins the connection URI with the table name.

For example, the dataset URI for `self._conn.uri = "s3://my-bucket/lancedb"` and `self.name = "my_table"` returns `"s3://my-bucket/lancedb/my_table.lance"`. This works fine for basic use cases without concurrent writes, but breaks for the `s3+ddb` scheme because Lance expects query parameters.

For the safe writes the `self._conn.uri = "s3+ddb://my-bucket/lancedb?ddbTableName=my-ddb-table"` and `self.name = "my_table"` breaks when joining to `"s3+ddb://my-bucket/lancedb?ddbTableName=my-ddb-table/my_table.lance"`. Notice how the table name is joined after the query parameters rather the base URI.

I need concurrent writes for my use case, so I just monkeypatched this and it has been working nicely with dynamodb via Lance's `s3+ddb` scheme!
```
import lancedb
from lancedb.table import LanceTable
from lancedb.util import join_uri

class ddbLanceTable(LanceTable):
    @property
    def _dataset_uri(self) -> str:
        base_uri, sep, query_params = self._conn.uri.partition("?")  # separate the base URI from the query parameters
        dataset_uri = join_uri(base_uri, f"{self.name}.lance")       # Join the table name to the base URI
        return sep.join([dataset_uri, query_params])                 # reconstruct new URI with query parameters

lancedb.table.LanceTable = ddbLanceTable                             # monkeypatch to enable concurrency-safe writer

conn = lancedb.connect("s3+ddb://my-bucket/lancedb?ddbTableName=my-ddb-table")
table = conn.create_table("my_table", data=[...], exist_ok=True)     # concurrent write with dynamodb...
```

So the `s3` case above still returns `"s3://my-bucket/lancedb/my_table.lance"` ✅ 
And the `s3+ddb` case now returns `"s3+ddb://my-bucket/lancedb/my_table.lance?ddbTableName=my-ddb-table"` ✅ 

Am I overlooking anything with my work-around? Would it be reasonable to propose the solution in a PR so I don't have to monkeypatch it? There might be a more official way to enable dynamodb commits in the Python SDK but this at least enables use of Lance's `s3+ddb` scheme/ dynamodb feature to unblock folks who need concurrency safe writes.

**Comment by wjones127** [comment]
> Am I overlooking anything with my work-around?

There a few places this won't work well:

1. We pass the `_dataset_uri` to PyArrow's `FileSystem.from_uri` in some places, which won't work with the `s3+ddb` scheme.
2. We use it in getting the path to the FTS index, which does a naive join of the path. Having the query parameters at the end will mess it up.

So I think we'd need to separate it out a bit. Maybe have one property `_dataset_path` that doesn't have the special `s3+ddb` scheme and query parameters. And the `_dataset_uri` that does. Then we can pass the appropriate one to each method. I'll try that out now.

**Comment by huffmanjohnf** [comment]
> We pass the _dataset_uri to PyArrow's FileSystem.from_uri in some places

Good point. I do have to use `s3_ddb` scheme for writes and `s3` separately for reads for that reason. 

> We use it in getting the path to the FTS index

Makes sense. Does the FTS index have S3 support? That's a separate capability I'm curious about outside of the scope of this issue.

> So I think we'd need to separate it out a bit...I'll try that out now.

Looking forward to seeing what you come up with! I think it'd be convenient to be able to use the `s3+ddb` and leverage the nice lance feature.

**Comment by wjones127** [comment]
> Does the FTS index have S3 support? That's a separate capability I'm curious about outside of the scope of this issue.

It does not. So I guess that is moot anyways.
