### ISSUE TITLE
Add `bypass_vector_index` to Python sync API

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#535]
We added this parameter to Node and Async Python in https://github.com/lancedb/lancedb/pull/1113.

* [ ] Add this to the Python sync API.
* [ ] Add a quick user guide on how to measure recall of a vector index using this.

This functionality is critical for debugging and measuring recall.

**Comment by westonpace** [comment]
Since you're thinking about the topic, how should we handle "use scalar indices".  Choices:

 * Just have a single `use_index` parameter that controls whether any kind of index is used
 * Have two boolean parameters, `use_scalar_index` and `use_index` (or `use_vector_index`)
 * Change `use_index` to accept a list of columns (or index names?) to use

**Comment by wjones127** [comment]
It's an interesting question. For ANN/KNN search, this flag doesn't just flip between using an index and not; it also determines whether the results are approximate or not (since ANN indexes are approximate by nature). I think that makes it a little different than the scalar index case, where results are exact either way, right?

For this reason, I think it makes sense to keep this separate. It seems to me that disabling scalar indices is mostly for debugging purposes right? Makes me wonder if we shouldn't expose it in primary APIs at all and instead control it with an environment variable or global setting. What would you think of that?
