### ISSUE TITLE
`db.table_names()` comes up empty on GCS

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#673]
From a user report:

```python
>>> import lancedb
>>> db = lancedb.connect("gs://xxxx/lance")
>>> db.table_names()
[]
>>> db.open_table("meta")
LanceTable(meta)
>>> t = db.open_table("meta")
>>> len(t.to_pandas())
11
>>>
```

We use PyArrow filesystems under the hood to introspect the bucket:

https://github.com/lancedb/lancedb/blob/b085d9aaa1ab95c0ba62b479a863bd850c9b0ae6/python/lancedb/db.py#L296-L298

However, PyArrow's `GCSFileSystem` is known to report common prefixes as empty if there isn't a "directory marker": https://github.com/apache/arrow/issues/32403 object-store-rs doesn't create these directory markers.

I suspect that is the underlying issue. We could either create the directory markers or we could use some other mechanism to list the bucket.

**Comment by sergiocorreia** [comment]
FWIW, I get the same error on a Windows installation (Win10+Py3.12), and for a different reason

Given a path `C:/foo/bar.lancedb`,  `get_uri_location()` returns `/foo/bar.lancedb` which then will obviously fail when passed to `filesystem.get_file_info()` because it's not a valid path or file.

If instead of doing

```python
paths = filesystem.get_file_info( 
     fs.FileSelector(get_uri_location(self.uri)) 
 )
```

We do:

```python
paths = filesystem.get_file_info( 
     fs.FileSelector(self.uri)
 )
```

Then the code works correctly, **on Windows**.

**Comment by westonpace** [comment]
The `table_names` feature should be fixed in https://github.com/lancedb/lancedb/pull/1059

**Comment by fekstr** [comment]
`table_names` still returns an empty list for me on GCS
