### ISSUE TITLE
LanceDBError: Commit conflict for version 8: Failed to commit the transaction after 5 retries.

### ISSUE THREAD

**Issue by archywillhe** [lancedb/lancedb#725]
Got this error while I was writing 500 entries with embedding.

Any good way to debug this?

**Comment by wjones127** [comment]
Hi @archywillhe. This error means that LanceDB tried to write your new rows 5 times, but failed because there was another concurrent writer that beat it. This can happen if you have too many processes writing into the same table at one time.

How are you writing your entries? We recommend *not* writing entries one at a time, but in bulk instead.

**Comment by archywillhe** [comment]
ooh I see; yeah I was firing too many writes at the same time (after I cached the embedding). 

Thanks for the explanation !
