### ISSUE TITLE
Feature: remote sdk do not pass hard coded vector column to backend

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#941]
### SDK

Python

### Description

We can infer vector columns from the query now. Remote SDK (Python / JS) doesn't need to code the vector column hard if users did not explicitly specify it. 

### ToDo

- change `vector_column_name` to be optional for `search` - both OSS and remote
- add tests to make sure Phalanx can accept remote search without the `vector_column_name` specified by the user
- make sure we present clear error msgs, e.g. when there are multiple vectors but user didn't specify which one to use for search
- add examples to guides

**Comment by QianZhu** [comment]
Our Python SDK is not using the Rust code in [[Rust] schema coerce and vector column inference](https://github.com/lancedb/lancedb/pull/476/files#top). We have https://github.com/lancedb/lancedb/issues/849 to address this. 

However, in order to get LanceDB Cloud GA, we can add the infer_col to sync Python API
